# Pull official base image
FROM node:16

# Set working directory
WORKDIR /app

# Add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# Copy dependency files
COPY package.json ./
COPY package-lock.json ./

# Install dependencies
RUN npm ci --silent

# Copy all application files
COPY . /app/

# Build the production application
RUN npm run build

# Install serve to serve the built application
RUN npm install -g serve

# Start the application on port 3000
CMD ["serve", "-s", "build", "-l", "3000"]
