# pull official base image
FROM node:16
# set working directory
WORKDIR /app
# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH
# install app dependencies
COPY package.json ./
COPY package-lock.json ./

# Install dependencies (axios, react-router-dom@6, @testing-library/react, @testing-library/jest-dom, @testing-library/user-event, babel-preset-react-app)
RUN npm install --silent --save-dev jest @testing-library/react @testing-library/jest-dom@^4.2.4 @types/testing-library__jest-dom @jest/globals @testing-library/user-event axios react-router-dom@6 babel-preset-react-app @babel/plugin-proposal-private-property-in-object

# Silent clean install of npm
RUN npm ci --silent
RUN npm install react-scripts@3.4.1 -g --silent
# add app
COPY . /app/

# Build production
RUN npm run build
RUN npm install -g serve

## Start the app on port 3000
CMD serve -s build -l 3000
