FROM python:3.10-slim
WORKDIR /code
COPY requirements.txt ./
RUN pip install --no-cache-dir --upgrade -r requirements.txt
COPY ./ /code/
CMD ["sh", "-c", "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"]
